spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy
    username: root
    password: "1118"
  application:
    name: bookservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: false
        namespace: c37ca01e-7448-4d04-9648-8da521f86464
    sentinel:
      transport:
        dashboard: localhost:8858